### ISSUE TITLE
screen of orginis and origins classes selection does not shows

### ISSUE THREAD

**Issue by kaserv** [EdwinMindcraft/origins-architectury#321] opened 2023-04-28 17:10 UTC
i don't know why but having the mod patchouli installed (which is used for some book info in different mods)
causes origins screen of selections to be omitted

if you use the command /origins get origins (name) 
it says its empty

**Comment by ChrysanthCow** [comment] 2024-05-03 02:50
Duplicate of #423

**Closed as completed by ChrysanthCow** 2024-05-03 02:50 UTC
