### ISSUE TITLE
Removed missing powers from origins server logs

### ISSUE THREAD

**Issue by Thysium** [EdwinMindcraft/origins-architectury#323] opened 2023-04-29 07:34 UTC
Hello, in my server log I see this, what can I do to solve the problem?

`[29avr.2023 09:22:40.052] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 5 missing powers from origins:enderian
[29avr.2023 09:22:40.052] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:lumberjack
[29avr.2023 09:22:40.052] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 6 missing powers from origins:feline
Hello, in my server log I see this, what can I do to solve the problem?

[29avr.2023 09:22:40.053] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:warrior
[29avr.2023 09:22:40.053] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 5 missing powers from origins:elytrian
[29avr.2023 09:22:40.054] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 5 missing powers from origins:shulk
[29avr.2023 09:22:40.054] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:cleric
[29avr.2023 09:22:40.054] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:explorer
[29avr.2023 09:22:40.054] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 7 missing powers from origins:merling
[29avr.2023 09:22:40.055] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 7 missing powers from origins:phantom
[29avr.2023 09:22:40.055] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:beastmaster
[29avr.2023 09:22:40.055] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:merchant
[29avr.2023 09:22:40.055] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 4 missing powers from origins:arachnid
[29avr.2023 09:22:40.056] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:rancher
[29avr.2023 09:22:40.056] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 7 missing powers from origins:blazeborn
[29avr.2023 09:22:40.056] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 5 missing powers from origins:avian
[29avr.2023 09:22:40.057] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:archer
[29avr.2023 09:22:40.057] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:farmer
[29avr.2023 09:22:40.057] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:miner
[29avr.2023 09:22:40.057] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:blacksmith
[29avr.2023 09:22:40.058] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:cook
[29avr.2023 09:22:40.058] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 2 missing powers from origins-classes:rogue`

**Comment by Darkmega18** [comment] 2023-07-19 06:39
ah crap. I appear to have this too. I'm not sure whats going on, because my origins and effects were working not too long ago... but maybe they broke when I updated forge? I'm not sure.

**Comment by Darkmega18** [comment] 2023-07-19 06:50
Strange. I backdated the mod from the 1.7.1.0 version to the 1.5.0.6 version, due to my origins just being simple spawn locations, start gear and some power stuff that was already present in 1.16.5 and the origins work now.
However the powers are still displaying as if they've had things removed. but a read through their power descriptions in selection shows that they're working properly again.... for now...
I really have no idea what's broken or how it's broken or if it's just random to do with other mods.

Although now it seems start gear "recurrent" bool is doing nothing. Aiyaaaaah.

**Comment by ChrysanthCow** [comment] 2023-07-19 13:42
@Darkmega18, you seem to be having a different issue entirely, as this one shouldn't affect the actual powers themselves. Please file a new issue and provide logs.

**Comment by ChrysanthCow** [comment] 2023-07-19 13:43
Duplicate of #247

**Closed as completed** 2023-07-19 13:43 UTC
