### ISSUE TITLE
Self glow does not working, multiple issues occur.

### ISSUE THREAD

**Issue by AngelOfCreation** [EdwinMindcraft/origins-architectury#304] opened 2023-03-20 20:27 UTC
When using the self_glow power, the glow around the player fails to appear. It does set the color when giving the player the glow effect, however the red and blue fields are inverted.
The following power will give the player a blue glow when given the status effect, and nothing more.
`{
    "type": "origins:self_glow",
    "use_teams": false,
    "red": 1.0,
    "green": 0.0,
    "blue": 0.0
}`

**Comment by EdwinMindcraft** [comment] 2023-03-23 10:55
First part is intended behavior, second part is a bug.
You cannot see yourself glow, but yes, red and blue were inverted in the code.

**Comment by AngelOfCreation** [comment] 2023-03-25 12:40
> First part is intended behavior, second part is a bug. You cannot see yourself glow, but yes, red and blue were inverted in the code.

Actually it's not intended behavior. I tested the fabric version and I could see the glow myself just fine.

**Comment by EdwinMindcraft** [comment] 2023-03-25 12:43
Apparently so, I made a mistake while porting the code.

**Comment by ChrysanthCow** [comment] 2023-07-24 12:06
Fixed in a prior release.

**Closed as completed by ChrysanthCow** 2023-07-24 12:06 UTC
Labels: bug, 1.19
