### ISSUE TITLE
Going through a portal breaks the "view origin" function [o]

### ISSUE THREAD

**Issue by ShiftyFly** [EdwinMindcraft/origins-architectury#424] opened 2024-03-10 19:01 UTC
I load into a creative world, and press [o], it shows my origin correctly
I go through a nether portal, and press [o] and is says 'you cannot have an origin'. 
I go back through the nether portal and press [o] again with the same results.
changing origin with an orb of origin does fix, until I go through a portal
i have not tested ender portals yet, but the portals of the "TARDIM" mod also break it.
game version: 1.18.2, running Forge 40.2.0 with mod version 1.5.0.1

**Comment by ChrysanthCow** [comment] 2024-03-13 07:44
Duplicate of #316

**Closed as completed** 2024-03-13 12:55 UTC
Labels: bug, 1.18
