### ISSUE TITLE
The origins menu doesn't appear at all on the server

### ISSUE THREAD

**Issue by EldenFrog** [EdwinMindcraft/origins-architectury#429] opened 2024-03-23 14:02 UTC
I wanted to make an origin server for me and my friends to play on, but for whatever reason it just doesn’t work on the server?? The server is 1.20.1 forge and everything seems to be working when I’m in singleplayer but when I log in and check my origin it says “you can not have any origins” and  the origin orb doesn’t work either (the origin choice menu doesn’t appear at all). Any help would be appreciated. I have no mods except for the origins mod itself and its dependencies

**Comment by ChrysanthCow** [comment] 2024-05-03 02:35
Duplicate of #423

**Closed as completed by ChrysanthCow** 2024-05-03 02:35 UTC
