### ISSUE TITLE
Scalacube server outputs the following error

### ISSUE THREAD

**Issue by JAMalcolmson** [EdwinMindcraft/origins-architectury#337] opened 2023-06-17 06:39 UTC
The log (which is insanely huge) is here:
[debug.log](https://github.com/EdwinMindcraft/origins-architectury/files/11778129/debug.log)

The relevant segment is thus:

[17Jun2023 05:47:08.804] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 5 missing powers from origins:enderian
[17Jun2023 05:47:08.805] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:lumberjack
[17Jun2023 05:47:08.805] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 6 missing powers from origins:feline
[17Jun2023 05:47:08.805] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:warrior
[17Jun2023 05:47:08.805] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 5 missing powers from origins:elytrian
[17Jun2023 05:47:08.806] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 5 missing powers from origins:shulk
[17Jun2023 05:47:08.806] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:cleric
[17Jun2023 05:47:08.806] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:explorer
[17Jun2023 05:47:08.806] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 7 missing powers from origins:merling
[17Jun2023 05:47:08.806] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 7 missing powers from origins:phantom
[17Jun2023 05:47:08.807] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:beastmaster
[17Jun2023 05:47:08.807] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:merchant
[17Jun2023 05:47:08.807] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 4 missing powers from origins:arachnid
[17Jun2023 05:47:08.807] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:rancher
[17Jun2023 05:47:08.808] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 7 missing powers from origins:blazeborn
[17Jun2023 05:47:08.808] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 5 missing powers from origins:avian
[17Jun2023 05:47:08.808] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:archer
[17Jun2023 05:47:08.808] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:farmer
[17Jun2023 05:47:08.808] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:miner
[17Jun2023 05:47:08.808] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:blacksmith
[17Jun2023 05:47:08.809] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 1 missing powers from origins-classes:cook
[17Jun2023 05:47:08.809] [main/ERROR] [io.github.apace100.origins.Origins/]: Removed 2 missing powers from origins-classes:rogue

**Comment by ChrysanthCow** [comment] 2023-07-19 13:43
Duplicate of #247

**Closed as completed by ChrysanthCow** 2023-07-19 13:43 UTC
