### ISSUE TITLE
1.18.2 Error with forge 40.0.47+

### ISSUE THREAD

**Issue by netcore10** [EdwinMindcraft/origins-architectury#158] opened 2022-04-14 14:08 UTC
1. Nothing but origins and forge is installed (forge 40.0.49)
2. create a new world
3. crash
[crash-2022-04-14_15.04.12-server.txt](https://github.com/EdwinMindcraft/origins-architectury/files/8489793/crash-2022-04-14_15.04.12-server.txt)

**Comment by EdwinMindcraft** [comment] 2022-04-14 14:09
Duplicate of #157, Downgrade for now, my gradle decided to die.

**Comment by netcore10** [comment] 2022-04-14 14:09
oh apologies! I searched before uploading, couldn't find it!

**Closed as completed** 2022-04-15 00:23 UTC
