### ISSUE TITLE
Origins Forge + MCA Reborn

### ISSUE THREAD

**Issue by Nekohanta** [EdwinMindcraft/origins-architectury#418] opened 2024-02-12 18:37 UTC
There are mods MCA Reborn and Origins forge. In the first window when creating a world opens MCA, and after origins. Is there any way to make them open the other way around? Since on the fabric version this is the way it should be. Origins first, and after creating a character from MCA. I haven't found a solution in the configs. Agree that it would make sense that you choose your origin first, and then create the character's appearance to fit those criteria. Thank you in advance)

**Comment by ChrysanthCow** [comment] 2024-02-21 21:08
The main issue with this is priority. We'd have to set our set gui code to run before others using event priority, I'm just unsure on if this'd cause other issues.

**Comment by ChrysanthCow** [comment] 2024-02-21 21:08
I'll take a look at MCA Reborn to see how they open their GUI, just to see how they do it.

**Comment by Nekohanta** [comment] 2024-02-25 10:49
Hi, thanks for the reply. Can I count on any feedback?

**Comment by ChrysanthCow** [comment] 2024-02-25 15:16
I'll be looking into Origins Forge again at the beginning of the next month, because looking at it constantly was a huge source of why I burnt out before.

As for how MCA Reborn does their system, they do it on world join.

**Comment by Nekohanta** [comment] 2024-02-26 22:56
Shouldn't origins have the same thing?

**Comment by ChrysanthCow** [comment] 2024-02-26 23:18
Origins handles it a little differently.. I think we and Origins Fabric handles it on tick if a value is present.

**Comment by EdwinMindcraft** [comment] 2024-02-26 23:36
The short answer is no, it's not realistically possible to open the other way around.

The main reason is that, when opening it first thing in large packs, the GUI might request to be open *before* the loading world overlay disappeared, which nullified the effect of the command.
Another solution was to send a message to the player to tell them to open the screen, which had a nasty habit of failing and just not opening the screen, meaning people would just go around immune from not having an origin, or it would show up for people that already *had* an origin, meaning they'd have to change their origin first thing when logging in.

All this leads to the broken mess of a system we have nowdays, which tries repeatedly to open the screen after we're basically sure the player has received the data it needs, until you select an origin.

Maybe these issues are fixed now. But I don't have the hardware necessary to test those issues, especially since they were unreliable to reproduce at best, and downright impossible to reproduce on LAN networks at worst.

**Closed as not planned** 2024-03-11 01:22 UTC
Labels: won't fix
