### ISSUE TITLE
[1.19.2]  Incompatibility with Villagers Recruit

### ISSUE THREAD

**Issue by benurecarmin** [EdwinMindcraft/origins-architectury#436] opened 2024-04-10 16:09 UTC
Hello, 

I'm not sure which mod cause it, but when Origins and Villager recruits are active, the game crash when  a bowman villager attack any mob because of a tick loop, sometimes on the arrow, sometimes on the mob, it's the only thing I've understood from the crash report.

I have differents crashs reports for the same crash circumstances, so there's multiple exemples.

[crash-2024-04-10_17.41.46-server.txt](https://github.com/EdwinMindcraft/origins-architectury/files/14934763/crash-2024-04-10_17.41.46-server.txt)
[crash-2024-04-10_17.14.26-server.txt](https://github.com/EdwinMindcraft/origins-architectury/files/14934764/crash-2024-04-10_17.14.26-server.txt)
[crash-2024-04-10_15.59.03-fml.txt](https://github.com/EdwinMindcraft/origins-architectury/files/14934765/crash-2024-04-10_15.59.03-fml.txt)
[crash-2024-04-10_17.49.26-server.txt](https://github.com/EdwinMindcraft/origins-architectury/files/14934766/crash-2024-04-10_17.49.26-server.txt)

**Comment by ChrysanthCow** [comment] 2024-04-19 02:17
Duplicate of #428. Will fix today.

**Closed as completed** 2024-04-19 02:58 UTC
