### ISSUE TITLE
[1.19.2] Origins:ignore_water doesn't work

### ISSUE THREAD

**Issue by Illios42** [EdwinMindcraft/origins-architectury#262] opened 2022-10-16 22:20 UTC
Using the latest origins version and forge 43.1.1. Basically origins with the ignore_water power type can still swim just not get into the swimming animation. Correct behavior would be to have them be able to walk under water like if there was nothing there iirc

**Comment by ChrysanthCow** [comment] 2023-07-22 14:23
Duplicate of #336

**Closed as completed by ChrysanthCow** 2023-07-22 14:23 UTC
