### ISSUE TITLE
craftable orb of origin 

### ISSUE THREAD

**Issue by BONEWEEVIL1** [EdwinMindcraft/origins-architectury#356] opened 2023-08-14 11:23 UTC
how do i make the orbe non craftable im in 1.18.2

**Comment by Illios42** [comment] 2023-08-29 06:51
You can use a mod like CraftTweaker to remove recipes. That's honestly not a question you should be spamming here in the issue reports though, so maybe close your tickets and ask on the Origins/a modding Discord next time.

**Comment by ChrysanthCow** [comment] 2023-08-31 04:23
Duplicate of #354, which was also asked.

> You can use a mod like CraftTweaker to remove recipes. That's honestly not a question you should be spamming here in the issue reports though, so maybe close your tickets and ask on the Origins/a modding Discord next time.

Illios42 said it best.

**Closed as not planned by ChrysanthCow** 2023-08-31 04:23 UTC
