### ISSUE TITLE
1.16.5 Water Damage applying when using Small Ships

### ISSUE THREAD

**Issue by toErIpNid** [EdwinMindcraft/origins-architectury#59] opened 2021-09-12 01:08 UTC
When using the ships from the Small Ships mod, races like Blazeborn and probably also Enderian take damage from sitting inside the ship. I've also posted this on the Small Ships issue page with no repsonse.

**Comment by EdwinMindcraft** [comment] 2021-09-12 07:11
Duplicate of #4, The small ships mod adds rideable entities that aren't *technically* (code-wise) boats. As such they are basically the equivalent of horses & pigs, not much I can do about it.
While anyone can fix this issue, hooking into a third-party mod that hasn't reached its end-of-life is:
* Frowned upon by most modders
* Prone to breaking if the right line changes in the mod.

With those given, fixing it would just make Origins more unstable.

**Closed as completed by EdwinMindcraft** 2021-09-12 07:11 UTC
