### ISSUE TITLE
[1.19.2] Snowballs are not affected by Modify Damage Taken

### ISSUE THREAD

**Issue by ChrysanthCow** [EdwinMindcraft/origins-architectury#307] opened 2023-03-26 10:12 UTC
My guess is that since there is no damage in the first place, the Forge event used for Modify Damage Taken does not fire. This should also apply to eggs.

This is ultimately not super important to fix imo, but it is a part of Blazeborn that isn't present in Forge.

**Comment by EdwinMindcraft** [comment] 2023-03-26 23:17
From what I can tell, something happens between `Entity.hurt` and `Entity.actuallyHurt`. Forge has hooks in actuallyHurt, maybe not in hurt.
I'll check when I have minecraft's source code in front of me.

**Comment by EdwinMindcraft** [comment] 2023-03-27 12:37
The issue is kinda dumb. To avoid staggering the player when it takes a snowball, the game actually prevents damage of 0 specifically to the Player. This doesn't happen in any other context, meaning any other entity with that power would take damage.

**Comment by EdwinMindcraft** [comment] 2023-03-27 14:50
Should be fixed in the latest version.

**Closed as completed by EdwinMindcraft** 2023-03-27 14:50 UTC
Labels: bug, 1.19
