### ISSUE TITLE
Origins:Classes incompatibility due to item duplication

### ISSUE THREAD

**Issue by cassowarycasper** [EdwinMindcraft/origins-architectury#216] opened 2022-07-27 16:01 UTC
Minecraft Version: 1.18.2
Please see: https://github.com/LimonBlaze/origins-classes-forge/issues/11 and https://github.com/LimonBlaze/origins-classes-forge/issues/15

Essentially, origins:starting_equipment is making it so that every time someone logs onto the server or dies and respawns, they get duplicate starting items.

**Comment by DaddyP1G** [comment] 2022-09-06 20:37
I'm also having this problem.   Nothing shows in logs.  Tried to set  "recurrent": false also doesn't work.

**Comment by ChrysanthCow** [comment] 2023-07-24 11:41
Duplicate of #345

**Closed as completed by ChrysanthCow** 2023-07-24 11:41 UTC
