### ISSUE TITLE
[1.19.2] origins "removes missing powers"

### ISSUE THREAD

**Issue by Pixel-Clay** [EdwinMindcraft/origins-architectury#330] opened 2023-05-19 16:57 UTC
i really dont know what the heck is going on

`[19:48:07] [main/ERROR] [io.gi.ap.or.Origins/]: Removed 1 missing powers from origins-classes:merchant
[19:48:07] [main/ERROR] [io.gi.ap.or.Origins/]: Removed 1 missing powers from origins-classes:rancher
[19:48:07] [main/ERROR] [io.gi.ap.or.Origins/]: Removed 7 missing powers from origins:blazeborn
[19:48:07] [main/ERROR] [io.gi.ap.or.Origins/]: Removed 5 missing powers from origins:avian
[19:48:07] [main/ERROR] [io.gi.ap.or.Origins/]: Removed 1 missing powers from origins-classes:archer
[19:48:07] [main/ERROR] [io.gi.ap.or.Origins/]: Removed 1 missing powers from origins-classes:farmer
[19:48:07] [main/ERROR] [io.gi.ap.or.Origins/]: Removed 1 missing powers from origins-classes:miner
[19:48:07] [main/ERROR] [io.gi.ap.or.Origins/]: Removed 1 missing powers from origins-classes:cook
[19:48:07] [main/ERROR] [io.gi.ap.or.Origins/]: Removed 1 missing powers from origins-classes:lumberjack
[19:48:07] [main/ERROR] [io.gi.ap.or.Origins/]: Removed 5 missing powers from origins:shulk
[19:48:07] [main/ERROR] [io.gi.ap.or.Origins/]: Removed 1 missing powers from origins-classes:cleric
[19:48:07] [main/ERROR] [io.gi.ap.or.Origins/]: Removed 7 missing powers from origins:merling
[19:48:07] [main/ERROR] [io.gi.ap.or.Origins/]: Removed 4 missing powers from origins:arachnid
[19:48:07] [main/ERROR] [io.gi.ap.or.Origins/]: Removed 1 missing powers from origins-classes:blacksmith
[19:48:07] [main/ERROR] [io.gi.ap.or.Origins/]: Removed 2 missing powers from origins-classes:rogue`

**Comment by LevitateGamer** [comment] 2023-06-07 01:32
Have you figured out the problem? I have the same issue.

**Comment by ChrysanthCow** [comment] 2023-07-19 00:52
This is a message that happens, but you can still play the game as normal.

For now, I'd ignore it, but I will be looking into a fix for 1.7.0.1

**Comment by ChrysanthCow** [comment] 2023-07-19 13:33
I've found the cause of this, and it should be solved in the next update.

It was a matter of incorrectly getting power counts.

**Comment by ChrysanthCow** [comment] 2023-07-19 13:44
Duplicate of #247

**Closed as completed by ChrysanthCow** 2023-07-19 13:44 UTC
Labels: bug, 1.19
